### PR TITLE
Return nothing for getter methods that are not supported

### LINKED ISSUE #200: Add better error messages for getter function which are not supported
It's a small thing but consider an unconstrained system
```julia
sys = @system(x' = Ax + Bu)
```
and try to access a nonexisting field, the error message could be improved.
```julia
stateset(a)
ERROR: MethodError: no method matching stateset(::LinearControlDiscreteSystem{Float64,Array{Float64,2},Array{Float64,2}})
Closest candidates are:
  stateset(::ConstrainedContinuousIdentitySystem) at C:\Users\wueli\.julia\dev\MathematicalSystems\src\systems.jl:71
  stateset(::ConstrainedDiscreteIdentitySystem) at C:\Users\wueli\.julia\dev\MathematicalSystems\src\systems.jl:71
  stateset(::ConstrainedLinearContinuousSystem) at C:\Users\wueli\.julia\dev\MathematicalSystems\src\systems.jl:327
  ...
Stacktrace:
 [1] top-level scope at none:0
```

For example we could return:
```julia
ERROR: the state set cannot be accessed for a system of  type `LinearControlDiscreteSystem` 
```

### PR DESCRIPTION
**Pull request by ueliwechsler**
closes #200 

Following the proposal of @schillic, I implemented a default case for all getters that returns `nothing` if the method is not implemented. Additionally, I tried to give the unit tests for discrete and continuous systems more structure (which resulted in a large PR...sorry 😁)

As a by-product, I also added the supertype `AbstractSystem` to the `SystemWithOutput` type.

### CODE REVIEW

**Comment by mforets** [comment]
> Would nothing work as a default "Universe" type with respect to the ReachabilityAnalysis API?

Yes, we can handle that easily by making a new dispatch on structs with a `Nothing` field, which should behave as if it was a `LazySets.Universe`.

In fact after parsing the user input, (linear) reachability algorithms normalize systems to only `x' = Ax` (LCS) or the canonical form `x' = Ax + u` (CLCCS) with state and input constraints on `x` and `u` respectively. This covers all relevant cases. The normalization step is currently implemented [here](https://github.com/JuliaReach/ReachabilityAnalysis.jl/blob/master/src/Continuous/normalization.jl#L255). But this normalization would also be useful for another package. I think a good idea is to port such normalization to MathematicalSystems.jl.

**Comment by blegat** [comment]
There could be a way to get an error too
```julia
function well_chosen_function_name(func::Function, system, args...)
    ret = func(system, args...)
    if ret === nothing
        error("$func is not implemented by $(typeof(system)).")
    end
    return ret
end
```

File: test/continuous.jl [hunk 1]
```diff
@@ -1,248 +1,301 @@
...
+stateInputPlusOne = add_one(state, input)
+stateInputNoisePlusOne = add_one(state, input, noise)
+
+# Scalar System
+a = 1.; b = 2.; c = 0.1; d = 3.; Xs = 1; Us = 2; Ws = 3; e = 2.;
+As = [a][:,:]; Bs = [b][:,:]; Cs = [c]; Ds = [d][:,:]; Es = [e][:,:]
+
+
+
 @testset "Continuous identity system" begin
```
Comment (schillic) [inline test/continuous.jl:36]: I learned something new here ([doc](https://docs.julialang.org/en/v1/stdlib/Test/#Test.@testset)): You can nest `@testset`s! In case of no error, it will just print the outer test sets. In case of an error, it will print the inner test sets as well. I just wanted to share this.

**Review by schillic — APPROVED** [review]

File: test/continuous.jl (hunk 1 above)
Comment (ueliwechsler) [reply test/continuous.jl:36]: Thanks for the review!
Yes, the nesting is nice, it makes the testing output so much neater.

**Review by mforets — APPROVED** [review]

**Comment by mforets** [comment]
Merging..
