### PR TITLE
Fix IdentityMultiple and improve docs

### LINKED ISSUE #47: Fix show of IdentityMultiple
See [this comment](https://github.com/JuliaReach/MathematicalSystems.jl/pull/45#issuecomment-447928356).

### PR DESCRIPTION
**Pull request by mforets**
Closes #47.

### CODE REVIEW

File: src/identity.jl [hunk 1]
```diff
@@ -10,31 +10,66 @@ A scalar multiple of the identity matrix of given order and numeric type.
...
+IdentityMultiple{Rational{Int64}} of value 1//1 and order 2
+
+julia> I2r + I2r
+IdentityMultiple{Rational{Int64}} of value 2//1 and order 2
+
+julia> 4*I2r
+IdentityMultiple{Rational{Int64}} of value 4//1 and order 2
+```
+
+To create the matrix with a value different than the default (`1.0`), there are
```
Comment (schillic) [inline src/identity.jl]:
```suggestion
To create the matrix with a value different from the default (`1.0`), there are
```

File: src/identity.jl [hunk 2]
```diff
@@ -43,25 +78,27 @@ struct IdentityMultiple{T} <: AbstractMatrix{T}
...
 
 function Base.show(io::IO, ::MIME"text/plain", 𝐼::IdentityMultiple{T}) where T
-    print(io, "Scalar multiple of the identity matrix of order $(𝐼.n):\n   ", 𝐼.M)
+    print(io, "$(typeof(𝐼)) of value $(𝐼.M.λ) and order $(𝐼.n)")
 end
 
 # callable identity matrix
 LinearAlgebra.I(n::Int, N=Float64) = IdentityMultiple(one(N)*I, n)
+
+LinearAlgebra.I(λ::Number, n::Int, N=Float64) = IdentityMultiple(λ*I, n)
```
Comment (schillic) [inline src/identity.jl]:
```suggestion
LinearAlgebra.I(λ::Number, n::Int, N=Float64) = IdentityMultiple(N(λ)*I, n)
```
`N` was not taken into account.

**Comment by mforets** [comment]
Thanks for the review :thumbsup:
