### PR TITLE
Different type parameters for matrices

### LINKED ISSUE #40: Systems with different type of A and B
Proposal: allowing continuous systems types (eg. linear control) where `A` and `B` are not necessarily of the same matrix type. 

Consider the following example:

```julia
julia> using MathematicalSystems, LazySets

julia> using LinearAlgebra

julia> A = rand(4, 4); B = rand(4, 2);

julia> X = rand(Hyperrectangle, dim=4);

julia> U = rand(Ball2, dim=2);

julia> ConstrainedLinearControlContinuousSystem(A, I, X, B*U)
ERROR: MethodError: no method matching ConstrainedLinearControlContinuousSystem(::Array{Float64,2}, ::UniformScaling{Int64}, ::Hyperrectangle{Float64}, ::La
zySets.LinearMap{Float64,Ball2{Float64},Float64,Array{Float64,2}})
Closest candidates are:
  ConstrainedLinearControlContinuousSystem(::MT<:AbstractArray{T,2}, ::MT<:AbstractArray{T,2}, ::ST, ::UT) where {T, MT<:AbstractArray{T,2}, ST, UT} at /Use
rs/forets/.julia/dev/MathematicalSystems/src/continuous.jl:173
Stacktrace:
 [1] top-level scope at none:0
```

One has to resort to the more verbose workaround (`Base.eye` is deprecated in v0.7), and that uses the dense identity:

```julia
julia> ConstrainedLinearControlContinuousSystem(A, Matrix{Float64}(I, size(B, 1), size(B, 1)), X, B*U)
ConstrainedLinearControlContinuousSystem{Float64,Array{Float64,2},Hyperrectangle{Float64},LazySets.LinearMap{Float64,Ball2{Float64},Float64,Array{Float64,2}
}}([0.126641 0.295817 0.824143 0.597537; 0.246435 0.792802 0.236372 0.22299; 0.724793 0.322774 0.180107 0.163799; 0.489959 0.479873 0.672082 0.211406], [1.0
 0.0 0.0 0.0; 0.0 1.0 0.0 0.0; 0.0 0.0 1.0 0.0; 0.0 0.0 0.0 1.0], Hyperrectangle{Float64}([-1.72253, 0.288111, -0.71392, 0.289299], [0.579642, 1.68419, 0.64
65, 0.469011]), LazySets.LinearMap{Float64,Ball2{Float64},Float64,Array{Float64,2}}([0.331066 0.536467; 0.16453 0.984765; 0.0877278 0.250847; 0.821922 0.710
158], Ball2{Float64}([-1.20626, -0.250679], 0.6379243916680202)))
```

### PR DESCRIPTION
**Pull request by mforets**
Closes #40.

### CODE REVIEW

**Comment by mforets** [comment]
Ok! I'll add a test that uses dense / sparse matrices.

For #44 one way would be to transform (in a new constructor) the `UniformScaling` to a sparse matrix..

File: test/runtests.jl [hunk 1]
```diff
@@ -1,5 +1,6 @@
 using MathematicalSystems, LazySets, TypedPolynomials
 using Compat, Compat.Test
+using SparseArrays
```
Comment (schillic) [inline test/runtests.jl]: This must be wrapped in a `VERSION` check for v0.6.

Comment (mforets) [reply test/runtests.jl]: Indeed, thanks for pointing that out. I'll make that change and then merge.
